const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcrypt");
const prisma = new PrismaClient();

// Helper function untuk menambahkan '0' di depan angka (padding)
const pad = (num, size) => String(num).padStart(size, "0");

async function main() {
  console.log("🔄 Start seeding...");

  // ========== RESET DATABASE ==========
  console.log("🗑️  Cleaning existing data...");
  // Hapus tabel 'anak' dulu (yang punya foreign key)
  // Pastikan ini tidak dikomentari agar transaksi lama terhapus
  await prisma.transactionItem.deleteMany({});
  await prisma.transaction.deleteMany({});

  // Baru hapus tabel 'induk'
  await prisma.product.deleteMany({});
  console.log("   ✓ Products deleted");
  await prisma.category.deleteMany({});
  console.log("   ✓ Categories deleted");
  await prisma.refreshToken.deleteMany({});
  console.log("   ✓ Refresh tokens deleted");
  await prisma.user.deleteMany({});
  console.log("   ✓ Users deleted");
  console.log("✅ All data has been reset!\n");

  // ========== 1. BUAT USERS ==========
  console.log("👥 Creating users...");
  const usersData = [
    { username: "admin", password: "admin123", role: 1 },
    { username: "arya", password: "admin123", role: 1 },
    { username: "budi", password: "kasir123", role: 0 },
  ];
  for (const userData of usersData) {
    const hashedPassword = await bcrypt.hash(userData.password, 10);
    await prisma.user.create({
      data: {
        username: userData.username,
        password: hashedPassword,
        role: userData.role,
      },
    });
    console.log(
      `   ✓ Created user: ${userData.username} (${
        userData.role === 1 ? "Admin" : "Kasir"
      })`
    );
  }
  console.log("✅ 3 users created!\n");

  // ========== 2. DATA KATEGORI & PRODUK ==========
  console.log("📦 Preparing categories and products...");
  const categoriesWithProducts = {
    "Makanan Ringan": {
      products: [
        "Chitato Sapi Panggang 68g",
        "Lays Rumput Laut 68g",
        "Oreo Original 133g",
        "Taro Net 36g",
        "Silverqueen 58g",
        "Pringles Original 107g",
        "Cheetos BBQ 75g",
        "Kacang Garuda 200g",
        "Biskuat Coklat 140g",
        "Roma Kelapa 300g",
        "Beng Beng 20g",
        "Wafer Tango 130g",
        "Richeese Nabati 145g",
        "Better Keju 120g",
        "Selamat Keripik Singkong 100g",
        "Kusuka Kacang Telur 180g",
        "Astor Wafer Roll 150g",
        "Good Time Cookies 72g",
        "Monde Butter Cookies 454g",
        "Khong Guan Crackers 650g",
        "Malkist Abon 135g",
        "Chiki Ball 55g",
        "Jetz Crackers 70g",
        "Smax Rings 60g",
        "Qtela Singkong 60g",
        "Piatos BBQ 80g",
        "Doritos Nacho 160g",
        "Krekers Bawang 150g",
        "Nissin Wafer 300g",
        "Gery Chocolatos 90g",
        "Nyam Nyam Wafer 25g",
        "Biscuit Marie Regal 230g",
        "Hup Seng Cream Crackers 428g",
        "Jacob's Cream Crackers 700g",
        "Better Choco Chips 80g",
        "Biskuat Susu 140g",
        "Ritz Crackers 100g",
        "Roma Sari Gandum 115g",
        "Monde Cookies 150g",
        "Fullo Wafer 50g",
        "Pocky Chocolate 47g",
        "Selamat Makaroni 70g",
        "Richoco Wafer 132g",
        "Kokola Chocolate 100g",
        "Astor Chocolate 150g",
        "Superstar Wafer 126g",
        "Tango Vanila 130g",
        "Goriorio Keju 110g",
        "Oops Chocolate 60g",
        "Chuba Chocolate 50g",
      ],
      priceRange: { min: 3000, max: 12000 },
    },
    Minuman: {
      products: [
        "Coca-Cola 330ml",
        "Sprite 330ml",
        "Fanta Jeruk 330ml",
        "Pepsi 330ml",
        "7Up 330ml",
        "Aqua Botol 600ml",
        "Le Minerale 600ml",
        "Ades 600ml",
        "Vit 600ml",
        "Club 600ml",
        "Teh Botol Sosro 250ml",
        "Teh Pucuk 350ml",
        "Fruit Tea 500ml",
        "Nu Green Tea 450ml",
        "Teh Gelas 180ml",
        "Ultra Milk Coklat 250ml",
        "Ultra Milk Plain 250ml",
        "Indomilk Coklat 190ml",
        "Frisian Flag 225ml",
        "Bear Brand 189ml",
        "Pocari Sweat 500ml",
        "Mizone 500ml",
        "Aquarius 500ml",
        "100 Plus 325ml",
        "Gatorade 500ml",
        "Good Day Cappuccino 250ml",
        "Nescafe Classic 240ml",
        "Kapal Api Signature 200ml",
        "ABC Susu 200ml",
        "Torabika Cappuccino 200ml",
        "Yakult 65ml",
        "Cimory Yogurt 250ml",
        "Vitacharm 1L",
        "Minute Maid Pulpy Orange 300ml",
        "Buavita Jeruk 1L",
        "Pulpy Orange 350ml",
        "Ichi Ocha 350ml",
        "Happy Jus 200ml",
        "Tebs Sparkling 330ml",
        "Big Cola 500ml",
        "Kopiko Coffee 240ml",
        "Extra Joss 45g",
        "Hemaviton 150ml",
        "Kratingdaeng 150ml",
        "M-150 150ml",
        "Nutrisari Jeruk 14g",
        "Marimas 8g",
        "Pop Ice 25g",
        "Floridina 350ml",
        "Frestea 500ml",
      ],
      priceRange: { min: 2000, max: 15000 },
    },
    "Kebutuhan Pokok": {
      products: [
        "Indomie Goreng",
        "Indomie Soto",
        "Mie Sedaap Goreng",
        "Mie Sedaap Kari",
        "Sarimi Ayam",
        "Supermi Ayam Bawang",
        "Pop Mie Ayam",
        "Pop Mie Pedas",
        "Mie Gelas Soto",
        "Lemonilo Mie",
        "Beras Sania 5kg",
        "Beras Pandan Wangi 5kg",
        "Beras IR64 5kg",
        "Beras Rojolele 5kg",
        "Beras Premium 5kg",
        "Minyak Bimoli 2L",
        "Minyak Sunco 2L",
        "Minyak Tropical 2L",
        "Minyak Filma 2L",
        "Minyak Fortune 2L",
        "Gula Gulaku 1kg",
        "Gula Manis 1kg",
        "Gula Pasir Lokal 1kg",
        "Gula Aren 500g",
        "Gula Merah 250g",
        "Telur Ayam Negeri 1kg",
        "Telur Ayam Kampung 10 butir",
        "Tepung Segitiga Biru 1kg",
        "Tepung Bogasari 1kg",
        "Tepung Kunci Biru 1kg",
        "Garam Refina 500g",
        "Garam Dapur 250g",
        "Mentega Blueband 200g",
        "Margarin Simas 200g",
        "Butter Anchor 227g",
        "SKM Indomilk",
        "SKM Carnation",
        "SKM Frisian Flag",
        "Kopi Kapal Api 165g",
        "Kopi ABC Susu 10x31g",
        "Teh Celup Sariwangi 25x1.9g",
        "Teh Sosro Celup 30x2g",
        "Teh Gopek 100g",
        "Susu Dancow 800g",
        "Susu Bendera 800g",
        "Kecap Bango 550ml",
        "Kecap ABC 520ml",
        "Saos Sambal ABC 335ml",
        "Saos Tomat Delmonte 340ml",
        "Sasa Penyedap 250g",
      ],
      priceRange: { min: 2500, max: 75000 },
    },
    "Perawatan Diri": {
      products: [
        "Sabun Lifebuoy",
        "Sabun Dettol",
        "Sabun Lux",
        "Sabun Nuvo",
        "Sabun Dove",
        "Shampoo Pantene",
        "Shampoo Clear",
        "Shampoo Sunsilk",
        "Shampoo Rejoice",
        "Shampoo Head & Shoulders",
        "Pepsodent Putih",
        "Pepsodent Herbal",
        "Close Up",
        "Ciptadent",
        "Formula",
        "Rexona Men",
        "Rexona Women",
        "Nivea Deo",
        "Vaseline Deo",
        "Dove Deo",
        "Dove Body Wash",
        "Lifebuoy Body Wash",
        "Nuvo Body Wash",
        "Lux Body Wash",
        "Biore Body Foam",
        "Vaseline Hand Body",
        "Citra Hand Body",
        "Nivea Body Lotion",
        "Wardah Body Lotion",
        "Marina Body Lotion",
        "Biore Facial Foam",
        "Garnier Facial Foam",
        "Ponds Facial Foam",
        "Wardah Facial Foam",
        "Ovale Facial Lotion",
        "Gatsby Hair Gel",
        "Gatsby Hair Wax",
        "Ellips Hair Vitamin",
        "Makarizo Hair Mask",
        "Emina Face Wash",
        "Pigeon Sabun Bayi",
        "Johnson Baby Shampoo",
        "Zwitsal Baby Powder",
        "My Baby Lotion",
        "Cussons Baby Cream",
        "Gillette Razor",
        "Veet Hair Removal",
        "Konicare Minyak Telon",
        "Cap Lang Kayu Putih",
        "Balsem Geliga",
      ],
      priceRange: { min: 5000, max: 35000 },
    },
    "Pembersih Rumah": {
      products: [
        "Sunlight Jeruk Nipis 755ml",
        "Mama Lime 800ml",
        "Ekonomi Sabun Cuci Piring 780ml",
        "Morning Fresh 400ml",
        "Axion 780ml",
        "Rinso Anti Noda 1.8kg",
        "Attack Deterjen 1.2kg",
        "Daia Deterjen 1.8kg",
        "So Klin Liquid 800ml",
        "Surf Excel 770g",
        "Molto Ultra 820ml",
        "Molto Pink 900ml",
        "Softener Downy 950ml",
        "Lavender Softener 1L",
        "Soklin Softener 900ml",
        "Wipol Karbol 780ml",
        "Super Pel Lavender 780ml",
        "Soklin Pembersih Lantai 800ml",
        "Mr. Muscle Lantai 800ml",
        "Harpic Pembersih Toilet 500ml",
        "Bayclin Pemutih 1L",
        "Chlorin Pemutih 500ml",
        "Proclin Pemutih 500ml",
        "Wings Pemutih 1L",
        "So Klin Pemutih 1L",
        "Kamper Kapur Barus",
        "Stella Pengharum Ruangan",
        "Glade Pengharum",
        "Baygon Spray 600ml",
        "Hit Anti Nyamuk 600ml",
        "Kispray Pewangi 318ml",
        "Downy Parfum Collection 850ml",
        "Molto Pewangi 820ml",
        "Pureco Pewangi 900ml",
        "Autan Lotion Anti Nyamuk",
        "Scotch Brite Spons",
        "Mama Lime Spons",
        "Spon Cuci Piring",
        "Tisu Magic",
        "Tissue Paseo",
        "Sabun Colek Ekonomi",
        "Sabun Batang So Klin",
        "Vixal Pembersih",
        "Cif Cream",
        "Mr. Muscle Glass Cleaner",
        "Kain Pel",
        "Sapu Lidi",
        "Kemoceng",
        "Sikat WC",
        "Tempat Sampah Kecil",
      ],
      priceRange: { min: 2000, max: 45000 },
    },
    "Obat-obatan": {
      products: [
        "Panadol Biru",
        "Panadol Extra",
        "Bodrex",
        "Bodrex Migra",
        "Oskadon",
        "Paramex",
        "Mixagrip",
        "Neozep",
        "Decolgen",
        "Procold",
        "Tolak Angin Cair",
        "Tolak Angin Tablet",
        "Antangin JRG",
        "Antangin Tablet",
        "Konicare",
        "Komix Herbal",
        "Komix OBH",
        "Woods Peppermint",
        "Strepsils",
        "FG Troches",
        "Promag",
        "Mylanta",
        "Polysilane",
        "Waisan",
        "Stomaklin",
        "Entrostop",
        "Diapet",
        "New Diatabs",
        "Imodium",
        "Guanistrep",
        "Hansaplast Strip",
        "Hansaplast Roll",
        "Betadine 30ml",
        "Betadine Plester",
        "Alkohol 70%",
        "Kapas Pembalut",
        "Kasa Steril",
        "Perban Gulung",
        "Rivanol",
        "Povidone Iodine",
        "Minyak Kayu Putih",
        "Balsem Otot",
        "Balsem Geliga",
        "Counterpain",
        "Salonpas",
        "Vicks Formula 44",
        "OBH Combi",
        "Bisolvon",
        "Actifed",
        "Silex Sirup",
      ],
      priceRange: { min: 3000, max: 25000 },
    },
    "Roti & Kue": {
      products: [
        "Sari Roti Sobek Coklat",
        "Sari Roti Tawar",
        "Sari Roti Sandwich",
        "Sari Roti Butter",
        "Sari Roti Keju",
        "Aoka Roti Panggang",
        "Mr. Bread",
        "Royal Bread",
        "Fuwa Fuwa Bread",
        "Serena Roti",
        "Tango Wafer Coklat",
        "Tango Wafer Vanila",
        "Tango Wafer Strawberry",
        "Gery Chocolatos",
        "Gery Saluut",
        "Beng Beng",
        "Beng Beng Caramel",
        "Beng Beng Maxx",
        "SilverQueen Chunky Bar",
        "Cadbury Dairy Milk",
        "Better Butter Cookies",
        "Better Choco Chips",
        "Monde Butter Cookies",
        "Monde Serena",
        "Roma Malkist",
        "Roma Kelapa",
        "Roma Sari Gandum",
        "Khong Guan Crackers",
        "Jacob's Crackers",
        "Hup Seng Crackers",
        "Nissin Wafer Roll",
        "Astor Wafer",
        "Superstar Wafer",
        "Fullo Wafer",
        "Richoco Wafer",
        "Good Time Cookies",
        "Oreo Vanilla",
        "Biskuat Susu",
        "Biskuat Coklat",
        "Marie Regal",
        "Pocky Chocolate",
        "Pocky Strawberry",
        "Pretz",
        "Chuba Chocolate",
        "Kokola",
        "Kue Lapis Legit",
        "Kue Bolu Kukus",
        "Brownies Amanda",
        "Cake Kukus",
        "Donat Mini",
      ],
      priceRange: { min: 2000, max: 20000 },
    },
    "Susu & Produk Susu": {
      products: [
        "Ultra Milk Coklat 250ml",
        "Ultra Milk Full Cream 1L",
        "Ultra Milk Low Fat 1L",
        "Ultra Milk Strawberry 200ml",
        "Ultra Milk Kopi 200ml",
        "Indomilk Coklat 190ml",
        "Indomilk Plain 190ml",
        "Indomilk Strawberry 190ml",
        "Frisian Flag Coklat 225ml",
        "Frisian Flag Full Cream 900ml",
        "Bear Brand 189ml",
        "Bearbrand White Tea 140ml",
        "Bearbrand Gold 140ml",
        "Anlene Gold 650g",
        "Anlene Actifit 600g",
        "Dancow Instant 800g",
        "Dancow Fortigro 1kg",
        "Dancow Batita 900g",
        "Enfagrow A+ 800g",
        "Lactogen 1 750g",
        "Bendera Coklat 800g",
        "Bendera Full Cream 800g",
        "Bendera Putih 800g",
        "Tropicana Slim Susu 500g",
        "Diabetasol 600g",
        "Yakult 5x65ml",
        "Yakult Light 5x65ml",
        "Cimory Yogurt Drink 250ml",
        "Cimory Squeeze 120g",
        "Elle & Vire Yogurt 125g",
        "SKM Indomilk Coklat 370g",
        "SKM Indomilk Putih 370g",
        "SKM Carnation 370g",
        "SKM Frisian Flag 370g",
        "SKM Cap Enak 370g",
        "Susu Diamond UHT 1L",
        "Susu Greenfields UHT 1L",
        "Cimory Fresh Milk 950ml",
        "KIN Fresh Milk 1L",
        "Milkuat 110ml",
        "Yeos Soya Bean 300ml",
        "Nutrisoy 320ml",
        "Soyjoy",
        "Vitasoy 1L",
        "SoyGood 1L",
        "Keju Kraft Singles 10s",
        "Keju Prochiz Gold 170g",
        "Keju Cheddar Anchor 2kg",
        "Keju Parmesan 80g",
        "Keju Cheesy 170g",
      ],
      priceRange: { min: 2500, max: 150000 },
    },
    "Bumbu Dapur": {
      products: [
        "Kecap Bango Manis 550ml",
        "Kecap ABC Manis 520ml",
        "Kecap Sedaap 550ml",
        "Kecap Nasional 600ml",
        "Kecap Cap Piring 600ml",
        "Kecap Asin ABC 135ml",
        "Kecap Asin Indofood 140ml",
        "Saos Sambal ABC 335ml",
        "Saos Tomat Delmonte 340ml",
        "Saos Tiram 150ml",
        "Sasa Penyedap Rasa 250g",
        "Royco Ayam 230g",
        "Royco Sapi 230g",
        "Masako Ayam 250g",
        "Masako Sapi 250g",
        "Bawang Putih Bubuk 100g",
        "Bawang Merah Goreng 100g",
        "Merica Bubuk 80g",
        "Lada Hitam 50g",
        "Kaldu Jamur 200g",
        "Kunyit Bubuk 50g",
        "Jahe Bubuk 50g",
        "Lengkuas Bubuk 50g",
        "Ketumbar Bubuk 50g",
        "Jinten 50g",
        "Cabe Bubuk 100g",
        "Cabe Rawit Kering 50g",
        "Cabe Merah Kering 50g",
        "Bon Cabe Level 10",
        "Bon Cabe Level 30",
        "Terasi ABC",
        "Petis Udang",
        "Bumbu Nasi Goreng Instan",
        "Bumbu Ayam Goreng Instan",
        "Bumbu Rendang Instan",
        "Indofood Bumbu Opor",
        "Indofood Bumbu Soto",
        "Racik Bumbu Rawon",
        "Racik Bumbu Gulai",
        "Racik Bumbu Lodeh",
        "Minyak Wijen 100ml",
        "Cuka Apel 300ml",
        "Cuka Masak 150ml",
        "Garam Himalaya 250g",
        "Garam Laut 500g",
        "Mentega Putih 250g",
        "Santan Kara 200ml",
        "Santan Instan Sasa 65ml",
        "Kelapa Parut Kering 100g",
        "Agar-agar Swallow",
      ],
      priceRange: { min: 2000, max: 25000 },
    },
    "Alat Tulis": {
      products: [
        "Pulpen Standard AE7",
        "Pulpen Snowman V5",
        "Pulpen Faster C600",
        "Ballpoint Pilot BP-1",
        "Ballpoint Zebra F-301",
        "Pensil 2B Staedtler",
        "Pensil 2B Faber Castell",
        "Pensil HB Kenko",
        "Pensil Warna 12",
        "Pensil Warna 24",
        "Penghapus Steadtler",
        "Penghapus Faber Castell",
        "Penghapus Joyko",
        "Penghapus Kenko",
        "Tipex Pen Kenko",
        "Spidol Whiteboard Snowman",
        "Spidol Whiteboard Standard",
        "Spidol Permanent Artline",
        "Spidol Warna 12",
        "Highlighter Stabilo",
        "Buku Tulis Sidu 38",
        "Buku Tulis 58 Lembar",
        "Buku Gambar A4",
        "Buku Folio 100 Lembar",
        "Binder B5 Joyko",
        "Penggaris 30cm Butterfly",
        "Penggaris Segitiga",
        "Jangka",
        "Busur Derajat",
        "Rautan Pensil",
        "Gunting Kecil",
        "Gunting Besar",
        "Cutter Kecil Joyko",
        "Cutter Besar Kenko",
        "Lem UHU Stick",
        "Lem Fox Putih 150g",
        "Lem Alteco",
        "Lem Castol",
        "Lakban Bening Daimaru",
        "Lakban Coklat Nachi",
        "Double Tape Kecil",
        "Double Tape Besar",
        "Isolasi Hitam Nitto",
        "Stapler Kecil Max",
        "Stapler Besar Kenko",
        "Isi Stapler No.10",
        "Isi Stapler No.3",
        "Paper Clip Joyko",
        "Binder Clip Kenko",
        "Map Plastik Kancing",
      ],
      priceRange: { min: 1000, max: 30000 },
    },
    "Perlengkapan Bayi": {
      products: [
        "Popok Merries NB",
        "Popok Merries S",
        "Popok Merries M",
        "Popok Merries L",
        "Popok Merries XL",
        "Popok Pampers NB",
        "Popok Pampers S",
        "Popok Pampers M",
        "Popok Pampers L",
        "Popok Mamypoko Royal Soft",
        "Pigeon Baby Soap",
        "Pigeon Baby Shampoo",
        "Pigeon Baby Lotion",
        "Pigeon Baby Oil",
        "Pigeon Baby Powder",
        "Johnson Baby Shampoo",
        "Johnson Baby Soap",
        "Johnson Baby Oil",
        "Johnson Baby Lotion",
        "Johnson Baby Powder",
        "Zwitsal Baby Cream",
        "Zwitsal Baby Powder",
        "Zwitsal Shampoo",
        "Zwitsal Baby Oil",
        "Zwitsal Lotion",
        "Cussons Baby Cream",
        "Cussons Baby Powder",
        "My Baby Lotion",
        "Sleek Baby Bottle Wash",
        "Sleek Sabun Cuci Botol",
        "Dot Bayi Pigeon",
        "Dot Bayi Avent",
        "Botol Susu Pigeon",
        "Botol Susu Dr. Brown",
        "Empeng Bayi",
        "Sikat Botol",
        "Sikat Gigi Bayi",
        "Pasta Gigi Bayi",
        "Kapas Bayi Medisoft",
        "Cotton Bud Bayi",
        "Tisu Basah Pigeon",
        "Tisu Basah Pampers",
        "Tisu Basah My Baby",
        "Baby Wipes Cussons",
        "Celemek Bayi",
        "Bedak Cair Baby",
        "Minyak Telon Konicare",
        "Minyak Telon My Baby",
        "Balsem Bayi Transpulmin",
        "Parfum Bayi Johnson",
      ],
      priceRange: { min: 10000, max: 120000 },
    },
    "Frozen Food": {
      products: [
        "Nugget Fiesta 500g",
        "Nugget So Good 400g",
        "Nugget Belfoods 500g",
        "Nugget Kanzler 450g",
        "Nugget Champ 500g",
        "Sosis So Good 375g",
        "Sosis Fiesta 375g",
        "Sosis Champ 375g",
        "Sosis Kanzler 360g",
        "Sosis Bratwurst 500g",
        "Bakso Ikan 500g",
        "Bakso Sapi 50 pcs",
        "Bakso Ayam 50 pcs",
        "Otak-otak 500g",
        "Siomay Frozen 20 pcs",
        "Kentang Goreng McCain 1kg",
        "Kentang Goreng Farm Frites 1kg",
        "Onion Ring 400g",
        "Tahu Bakso 10 pcs",
        "Tahu Isi 10 pcs",
        "Dumpling Kulit 20 pcs",
        "Dimsum Ayam 10 pcs",
        "Hakao Udang 10 pcs",
        "Siomay Ayam 10 pcs",
        "Lumpia Mini 20 pcs",
        "Risol Mayo 5 pcs",
        "Risol Ragout 5 pcs",
        "Pastel Mini 10 pcs",
        "Lemper Frozen 5 pcs",
        "Kroket Kentang 5 pcs",
        "Pizza Mini 4 pcs",
        "Pizza Slice",
        "Lasagna",
        "Spaghetti Bolognese",
        "Mac & Cheese",
        "Chicken Wing 500g",
        "Chicken Popcorn 250g",
        "Fish Finger 250g",
        "Fish Nugget 250g",
        "Crab Stick 250g",
        "Udang Breaded 250g",
        "Cumi Ring 250g",
        "Scallop 250g",
        "Tempura Udang 250g",
        "Kakap Fillet 500g",
        "Edamame 500g",
        "Mixed Vegetables 500g",
        "Brokoli Frozen 500g",
        "Jagung Manis Pipil 500g",
        "Kacang Polong 500g",
      ],
      priceRange: { min: 15000, max: 80000 },
    },
    "Buah & Sayur": {
      products: [
        "Apel Fuji 1kg",
        "Apel Malang 1kg",
        "Apel Washington 1kg",
        "Jeruk Pontianak 1kg",
        "Jeruk Mandarin 1kg",
        "Pisang Ambon 1 sisir",
        "Pisang Cavendish 1 sisir",
        "Mangga Harum Manis 1kg",
        "Alpukat Mentega 1kg",
        "Anggur Merah 500g",
        "Semangka 1 buah",
        "Melon 1 buah",
        "Pepaya California 1 buah",
        "Nanas Madu 1 buah",
        "Salak Pondoh 1kg",
        "Bayam 1 ikat",
        "Kangkung 1 ikat",
        "Sawi Hijau 1 ikat",
        "Brokoli 500g",
        "Kembang Kol 500g",
        "Wortel 500g",
        "Kentang 1kg",
        "Tomat 500g",
        "Timun 500g",
        "Terong Ungu 500g",
        "Buncis 250g",
        "Kacang Panjang 1 ikat",
        "Cabe Merah Keriting 250g",
        "Cabe Rawit 100g",
        "Bawang Merah 250g",
        "Bawang Putih 250g",
        "Daun Bawang 1 ikat",
        "Seledri 1 ikat",
        "Jahe 250g",
        "Kunyit 250g",
        "Lengkuas 250g",
        "Serai 1 ikat",
        "Daun Salam 1 ikat",
        "Jeruk Nipis 250g",
        "Jagung Manis 2 buah",
        "Labu Siam 500g",
        "Kol 1 buah",
        "Tauge 250g",
        "Jamur Tiram 200g",
        "Selada 200g",
        "Paprika Merah 1 buah",
        "Paprika Hijau 1 buah",
        "Lobak 500g",
        "Ubi Jalar 1kg",
        "Singkong 1kg",
      ],
      priceRange: { min: 5000, max: 40000 },
    },
    "Daging & Seafood": {
      products: [
        "Ayam Potong 1 ekor",
        "Ayam Fillet Dada 500g",
        "Ayam Fillet Paha 500g",
        "Ceker Ayam 500g",
        "Sayap Ayam 500g",
        "Hati Ayam 250g",
        "Ati Ampela 5 pasang",
        "Daging Sapi Giling 500g",
        "Daging Rendang 1kg",
        "Iga Sapi 1kg",
        "Buntut Sapi 1kg",
        "Daging Slice 500g",
        "Tetelan Sapi 500g",
        "Paru Sapi 500g",
        "Kikil Sapi 500g",
        "Ikan Lele 1kg",
        "Ikan Nila 1kg",
        "Ikan Gurame 1kg",
        "Ikan Mas 1kg",
        "Ikan Kembung 1kg",
        "Ikan Tongkol 1kg",
        "Ikan Tuna Fillet 500g",
        "Ikan Salmon Fillet 200g",
        "Udang Pancet 500g",
        "Udang Vaname 500g",
        "Cumi-cumi 500g",
        "Kerang Hijau 1kg",
        "Kerang Dara 1kg",
        "Kepiting 1kg",
        "Rajungan 1kg",
        "Sosis Sapi 500g",
        "Sosis Ayam 500g",
        "Bakso Sapi 50 pcs",
        "Bakso Ikan 50 pcs",
        "Kornet Sapi 340g",
        "Daging Kambing 1kg",
        "Iga Kambing 1kg",
        "Patin Fillet 500g",
        "Gindara Fillet 500g",
        "Bandeng Presto 2 ekor",
        "Ikan Asin Jambal 250g",
        "Ikan Teri Medan 100g",
        "Cumi Asin 100g",
        "Telur Ikan 250g",
        "Kepala Ikan Kakap",
        "Kulit Ayam 500g",
        "Tulang Ayam 1kg",
        "Daging Kerbau 1kg",
        "Ikan Bawal 1kg",
        "Belut 500g",
      ],
      priceRange: { min: 15000, max: 150000 },
    },
    "Elektronik Kecil": {
      products: [
        "Lampu LED Philips 10W",
        "Lampu LED Hannochs 12W",
        "Baterai ABC AA 4pcs",
        "Baterai ABC AAA 4pcs",
        "Baterai Alkaline AA 2pcs",
        "Stop Kontak 4 Lubang",
        "Kabel Roll 10m",
        "Charger HP USB-C",
        "Kabel Data Micro USB",
        "Headset Murah",
        "Earphone Bluetooth",
        "Mouse Wireless",
        "Mousepad",
        "Kipas Angin USB",
        "Senter LED",
        "Lampu Emergency",
        "Adaptor Universal",
        "Setrika Listrik Philips",
        "Hair Dryer Panasonic",
        "Catokan Rambut",
        "Blender Mini",
        "Mixer Tangan Miyako",
        "Rice Cooker Mini Cosmos",
        "Pemanas Air",
        "Teko Listrik",
        "Timbangan Dapur Digital",
        "Timbangan Badan Digital",
        "Jam Weker Digital",
        "Kalkulator Citizen",
        "Speaker Bluetooth Mini",
        "Power Bank 10000mAh",
        "Lampu Tidur",
        "Lampu Belajar",
        "Raket Nyamuk",
        "Bel Rumah Wireless",
        "Remote TV Universal",
        "Antena TV Indoor",
        "Terminal Kuningan",
        "Steker T",
        "Bohlam Pijar 5W",
        "Lampu Hias Tumblr",
        "Dispenser Mini",
        "Kabel HDMI 1.5m",
        "Kabel Audio AUX",
        "Kipas Angin Jepit",
        "Pencukur Kumis Elektrik",
        "VGA to HDMI Converter",
        "USB Hub 4 Port",
        "Kartu Memori 32GB",
        "Flashdisk 16GB",
      ],
      priceRange: { min: 10000, max: 250000 },
    },
    "Peralatan Dapur": {
      products: [
        "Wajan Teflon Maxim",
        "Panci Stainless Steel",
        "Spatula Silikon",
        "Sodet Kayu",
        "Centong Nasi",
        "Pisau Dapur Oxone",
        "Talenan Plastik",
        "Mangkok Melamin",
        "Piring Keramik",
        "Gelas Kaca",
        "Sendok Makan 6pcs",
        "Garpu 6pcs",
        "Sumpit Bambu 10 pasang",
        "Parutan Keju",
        "Pembuka Kaleng",
        "Pembuka Botol",
        "Saringan Teh",
        "Saringan Santan",
        "Cobek dan Ulekan",
        "Bakul Nasi",
        "Termos Air Panas",
        "Toples Kaca",
        "Rak Piring Stainless",
        "Botol Minum Tupperware",
        "Kotak Makan",
        "Cetakan Es Batu",
        "Cetakan Agar-agar",
        "Lap Dapur",
        "Serbet Makan",
        "Teko Plastik",
        "Gelas Ukur",
        "Timbangan Kue",
        "Rolling Pin",
        "Kuas Kue",
        "Loyang Bolu",
        "Cetakan Kue Kering",
        "Gilingan Daging Manual",
        "Panci Presto",
        "Wadah Bumbu",
        "Tusuk Sate 100pcs",
        "Spons Cuci Piring",
        "Sabut Baja",
        "Rak Bumbu",
        "Tutup Gelas",
        "Alas Panci",
        "Celemek Masak",
        "Sarung Tangan Oven",
        "Penjepit Makanan",
        "Pengocok Telur",
        "Pisau Buah",
      ],
      priceRange: { min: 8000, max: 150000 },
    },
    "Mainan Anak": {
      products: [
        "Mobil-mobilan Hot Wheels",
        "Boneka Barbie",
        "Robot Transformer",
        "Lego Classic",
        "Puzzle Anak",
        "Bola Plastik",
        "Pistol Air",
        "Yoyo",
        "Gasing",
        "Congklak",
        "Ular Tangga",
        "Ludo",
        "Kartu Uno",
        "Kartu Remi",
        "Monopoli",
        "Plastisin",
        "Pasir Kinetik",
        "Buku Mewarnai",
        "Crayon 12 Warna",
        "Pensil Warna",
        "Skuter Anak",
        "Sepeda Roda Tiga",
        "Helm Anak",
        "Bubble Gun",
        "Mainan Masak-masakan",
        "Mainan Dokter-dokteran",
        "Balok Kayu",
        "Rubik 3x3",
        "Bola Bekel",
        "Kelereng",
        "Action Figure Ultraman",
        "Mainan Edukasi Anak",
        "Baby Walker",
        "Mainan Musik Bayi",
        "Tenda Anak",
        "Topeng Karakter",
        "Layang-layang",
        "Stiker Anak",
        "Buku Cerita Anak",
        "Slime",
        "Soft Gun",
        "Gelang Karet",
        "Gantungan Kunci Lucu",
        "Celengan Karakter",
        "Papan Tulis Mini",
        "Kacamata Mainan",
        "Jam Tangan Anak",
        "Walkie Talkie Mainan",
        "Miniatur Hewan",
        "Keyboard Mainan",
      ],
      priceRange: { min: 5000, max: 100000 },
    },
    "Aksesoris Fashion": {
      products: [
        "Kaos Kaki Dewasa",
        "Kaos Kaki Anak",
        "Sarung Tangan Motor",
        "Masker Kain",
        "Topi Baseball",
        "Kacamata Hitam",
        "Ikat Pinggang Pria",
        "Ikat Pinggang Wanita",
        "Dompet Kulit Pria",
        "Dompet Wanita",
        "Gantungan Kunci",
        "Jepit Rambut",
        "Ikat Rambut",
        "Bando",
        "Syal",
        "Pashmina",
        "Bros Hijab",
        "Peniti Bohlam",
        "Ciput Rajut",
        "Manset Tangan",
        "Gelang Tali",
        "Kalung Titanium",
        "Anting-anting",
        "Cincin",
        "Tali Sepatu",
        "Semir Sepatu",
        "Sikat Sepatu",
        "Payung Lipat",
        "Jas Hujan Plastik",
        "Gembok Koper",
        "Tas Belanja Lipat",
        "Goodie Bag",
        "Stiker Baju",
        "Patch Bordir",
        "Tali Jam Tangan",
        "Saputangan",
        "Kipas Tangan",
        "Sajadah Travel",
        "Peci Rajut",
        "Tasbih Digital",
        "Korek Api",
        "Sarung",
        "Ikat Kepala",
        "Bandana",
        "Buff Multifungsi",
        "Kaus Dalam Pria",
        "Singlet Wanita",
        "Legging Anak",
        "Stocking",
        "Tote Bag Kanvas",
      ],
      priceRange: { min: 7000, max: 75000 },
    },
    "Produk Herbal": {
      products: [
        "Tolak Angin Cair",
        "Antangin JRG",
        "Madu TJ Murni",
        "Madu Rasa",
        "Sari Kurma",
        "Habbatussauda",
        "Minyak Zaitun",
        "Jamu Kunyit Asam",
        "Jamu Beras Kencur",
        "Teh Herbal",
        "Teh Daun Jati Cina",
        "Teh Bunga Telang",
        "Jahe Merah Instan",
        "Temulawak Bubuk",
        "Susu Etawa",
        "Spirulina Kapsul",
        "Gamat Emas",
        "Propolis",
        "Minyak Angin Aromatherapy",
        "Salep Kulit 88",
        "Obat Batuk Herbal",
        "Obat Masuk Angin",
        "Pegal Linu Kapsul",
        "Jamu Kuat Pria",
        "Jamu Pelangsing",
        "Masker Wajah Organik",
        "Lulur Tradisional",
        "Sabun Herbal",
        "Shampo Lidah Buaya",
        "Minyak Kemiri",
        "Minyak Bulus",
        "Minyak Tawon",
        "Kapsul Daun Kelor",
        "Kapsul Purwoceng",
        "Kapsul Pasak Bumi",
        "Sari Lemon",
        "Cuka Apel",
        "Garam Himalaya",
        "Teh Hijau",
        "Kopi Hijau",
        "Kopi Ginseng",
        "Madu Hitam Pahit",
        "Sarang Walet",
        "Ekstrak Kulit Manggis",
        "Ekstrak Daun Sirsak",
        "Permen Jahe",
        "Permen Tolak Angin",
        "Wedang Uwuh",
        "Wedang Ronde",
        "Sekoteng Instan",
      ],
      priceRange: { min: 6000, max: 90000 },
    },
    "Perlengkapan Hewan": {
      products: [
        "Whiskas Adult 400g",
        "Whiskas Junior 400g",
        "Friskies 500g",
        "Royal Canin Kitten 400g",
        "Me-O Adult 1.2kg",
        "Bolt Cat Food 1kg",
        "Excel Cat Food 500g",
        "Pedigree Adult 1.5kg",
        "Dog Choice 1kg",
        "Alpo Dog Food 1.5kg",
        "Pasir Kucing Gumpal 5L",
        "Pasir Zeolit No. 2",
        "Shampo Kucing",
        "Shampo Anjing",
        "Kalung Kucing",
        "Kalung Anjing",
        "Mainan Bola Kucing",
        "Mainan Anjing",
        "Tempat Makan Hewan",
        "Botol Minum Gantung",
        "Serokan Pasir",
        "Kandang Hamster",
        "Makanan Hamster",
        "Serbuk Kayu Hamster",
        "Makanan Kelinci",
        "Makanan Ikan Cupang",
        "Pelet Ikan Lele",
        "Obat Kutu Kucing",
        "Obat Cacing Anjing",
        "Vitamin Hewan",
        "Susu Kucing",
        "Susu Anjing",
        "Snack Kucing",
        "Snack Anjing",
        "Tali Tuntun Anjing",
        "Harness Kucing",
        "Gunting Kuku Hewan",
        "Sikat Gigi Hewan",
        "Akuarium Mini",
        "Batu Aerator",
        "Filter Gantung Aquarium",
        "Lampu Aquarium",
        "Pakan Burung Kenari",
        "Pakan Burung Lovebird",
        "Millet Putih",
        "Voer Kasar",
        "Kandang Burung",
        "Tempat Minum Burung",
        "Obat Jamur Ikan",
        "Garam Ikan",
      ],
      priceRange: { min: 10000, max: 150000 },
    },
  };

  let allProductsData = [];
  for (const categoryName of Object.keys(categoriesWithProducts)) {
    // Buat kategori di DB
    const category = await prisma.category.create({
      data: { name: categoryName },
    });
    console.log(`   ✓ Created category: ${category.name}`);

    const categoryData = categoriesWithProducts[categoryName];
    const products = categoryData.products;
    const priceRange = categoryData.priceRange;
    let productCounter = 1;

    // Loop untuk setiap produk di kategori ini
    for (const productName of products) {
      const costPrice =
        Math.floor(Math.random() * (priceRange.max - priceRange.min + 1)) +
        priceRange.min;

      // === LOGIKA PEMBUATAN KODE PRODUK ===
      const paddedCategoryId = pad(category.id, 3);
      const paddedProductNumber = pad(productCounter, 3);
      const productCode = `${paddedCategoryId}-${paddedProductNumber}`;

      allProductsData.push({
        code: productCode,
        name: productName,
        costPrice: costPrice,
        sellingPrice: costPrice + Math.floor(costPrice * 0.3),
        stock: Math.floor(Math.random() * 100) + 10,
        categoryId: category.id,
      });
      productCounter++;
    }
  }

  // Masukkan semua produk ke database sekaligus
  await prisma.product.createMany({
    data: allProductsData,
  });
  console.log(`✅ ${allProductsData.length} products created!\n`);

  // ========== 3. BUAT TRANSAKSI REALISTIS ==========
  console.log("🛒 Creating realistic transactions...");

  // Ambil semua produk dan user kasir dari DB
  const allProducts = await prisma.product.findMany();
  const cashiers = await prisma.user.findMany({ where: { role: 0 } });

  if (allProducts.length === 0 || cashiers.length === 0) {
    console.log(
      "⚠️  Cannot create transactions without products or cashiers. Skipping."
    );
  } else {
    const transactionsToCreate = [];

    // Tentukan rentang tanggal untuk tahun 2025
    const startDate = new Date("2025-01-01T00:00:00Z");
    const endDate = new Date("2025-12-31T23:59:59Z");
    const dateRange = endDate.getTime() - startDate.getTime();

    // Buat 5000 transaksi acak selama tahun 2025
    for (let i = 0; i < 5000; i++) {
      // Pilih kasir secara acak
      const cashier = cashiers[Math.floor(Math.random() * cashiers.length)];

      // Pilih tanggal & waktu acak dalam rentang tahun 2025
      const transactionDate = new Date(
        startDate.getTime() + Math.random() * dateRange
      );

      // Tentukan jumlah item dalam transaksi ini (antara 1 sampai 5)
      const itemCount = Math.floor(Math.random() * 5) + 1;
      const items = [];

      // Ambil produk unik untuk transaksi ini
      const productPool = [...allProducts]; // Salin array agar bisa di-mutate
      for (let j = 0; j < itemCount; j++) {
        if (productPool.length === 0) break;

        // Pilih produk acak dari pool
        const productIndex = Math.floor(Math.random() * productPool.length);
        const selectedProduct = productPool[productIndex];

        // Hapus produk dari pool agar tidak terpilih lagi di transaksi yang sama
        productPool.splice(productIndex, 1);

        const quantity = Math.floor(Math.random() * 3) + 1; // Beli 1-3 item

        items.push({
          // Data untuk TransactionItem
          productId: selectedProduct.id, // Relasi ke produk
          quantity: quantity, // Jumlah item
          sellingPrice: selectedProduct.sellingPrice, // Harga jual saat itu
          costPrice: selectedProduct.costPrice, // Harga modal saat itu
          subtotal: selectedProduct.sellingPrice * quantity, // Subtotal untuk item ini
        });
      }

      // Buat data transaksi
      if (items.length > 0) {
        // Hitung total dari semua subtotal item
        const total = items.reduce((acc, item) => acc + item.subtotal, 0);

        // Simulasi pembayaran (misal, dibulatkan ke 5000 atau 10000 terdekat)
        const pay = Math.ceil(total / 5000) * 5000;
        const change = pay - total;

        const transaction = await prisma.transaction.create({
          data: {
            // Data untuk Transaction
            userId: cashier.id,
            total: total,
            pay: pay,
            change: change,
            createdAt: transactionDate,
            // Buat TransactionItem terkait secara nested
            items: {
              create: items.map((item) => ({
                productId: item.productId,
                quantity: item.quantity,
                sellingPrice: item.sellingPrice,
                costPrice: item.costPrice,
								subtotal: item.subtotal,
								createdAt: transactionDate,
              })),
            },
          },
        });
        transactionsToCreate.push(transaction);
      }
    }
    console.log(`✅ ${transactionsToCreate.length} transactions created!\n`);
  }

  console.log("Seeding finished. 🌱");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
